### ISSUE TITLE
Inotify error -1 

### ISSUE THREAD

**Issue by SrAndromeda** [martinkirch/drop2beets#3]
I'm trying to use beets as auto-tagger for music downloaded from different sources. Each source put the files on one subfolder, and i'm hopping to use this plugin for automatic clasification.
My problem is, when i try to launch "beet dropbox", a exception is raised. It looks like is produced by inotify. My environment is a docker container, which i suppose is the mainly problem, but i'm not really sure. Here is the output

beet dropbox
Traceback (most recent call last):
  File "/usr/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/config/drop2beets/beetsplug/drop2beets.py", line 93, in _main
    i = InotifyTree(self.dropbox_path)
  File "/config/.local/lib/python3.10/site-packages/inotify/adapters.py", line 340, in __init__
    self.__load_tree(path)
  File "/config/.local/lib/python3.10/site-packages/inotify/adapters.py", line 362, in __load_tree
    self._i.add_watch(path, self._mask)
  File "/config/.local/lib/python3.10/site-packages/inotify/adapters.py", line 95, in add_watch
    wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
  File "/config/.local/lib/python3.10/site-packages/inotify/calls.py", line 34, in _check_nonnegative
    raise InotifyError("Call failed (should not be -1): (%d)" % 
inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)

**Comment by martinkirch** [comment]
The `inotify` package behind [has not been updated for 5 years](https://pypi.org/project/inotify/) so it could be the culprit too.
I guess that's a motivating example for #2 , will try to look into it asap

**Comment by martinkirch** [comment]
I've published a new version of `drop2beets`, using a more modern (and portable) library.
You can get it with `pip install -U drop2beets`.

does it works better ?
